name: Test Notebooks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Run notebooks
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nbformat nbconvert

      - name: Run notebooks
        run: python ./dev/notebook_runner.py notebooks
