name: Test Notebooks
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Run notebooks
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nbformat nbconvert

      - name: Run notebooks
        run: | 
          cd notebooks
          python ../dev/notebook_runner.py .
