name: Test Notebooks
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Run notebooks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scipy numpy tvb-library ebrains_drive ipywidgets==7.7.2
          python -m pip install pythreejs pyvista colorcet plotly
          python -m pip install ipympl mne
          python -m pip install tvb-data
          python -m pip install nbformat nbconvert
          python -m pip install tvb-framework
          python -m pip install dask
          python -m pip install "dask[distributed]" --upgrade

      - name: Run notebooks
        uses: coactions/setup-xvfb@v1
        with:
          run: python ./dev/notebook_runner.py notebooks
